TARGET = XCORE-AI-EXPLORER
APP_NAME = test
USED_MODULES = lib_dsp(>=4.0.0)
XCC_FLAGS = -O2 -g -report -DDEBUG_PRINT_ENABLE=1
VERBOSE = 0

XMOS_MAKE_PATH ?= ../..
-include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
