def configure(conf):
    conf.load('compiler_xcc', tooldir='../../../build_tools/xwaf')


def build(bld):
    bld.env.TARGET_ARCH = 'XCORE-200-EXPLORER'
    bld.env.XCC_FLAGS = ['-O2', '-g', '-report', '-DDEBUG_PRINT_ENABLE=1']

    # Build our program
    prog = bld.program(target='bin/test.xe', depends_on='lib_dsp(>=3.0.0)')
